name: Build Spotifuck (Apktool)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Build Tools
        run: |
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -O apktool.jar
          wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar -O uber-apk-signer.jar

      - name: Recompile APK with Apktool
        run: java -jar apktool.jar b . -o spotifuck-unsigned.apk

      - name: Sign the APK
        run: java -jar uber-apk-signer.jar -a spotifuck-unsigned.apk -o final-apk/

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Spotifuck-Signed-APK
          path: final-apk/*.apk
          
